name: RYDEN_REMOTE_EXECUTION
on: workflow_dispatch

jobs:
  execute_strategy:
    runs-on: ubuntu-latest
    steps:
      - name: API_HANDSHAKE
        run: |
          curl -X POST https://ryden-core.rajatdatta90000.workers.dev/api/v1/x/automate \
          -H "X-RYDEN-APP-KEY: ${{ secrets.RYDEN_APP_KEY }}" \
          -H "Content-Type: application/json"
